name: Report a bug
description: Encountered a bug? Report it here
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
     value: |
      Many thanks in advance for your help. Nevertheless, we need some information to help us.
  - type: dropdown
    attributes:
      label: Operating system
      options:
        - Windows
        - macOS
        - Linux (Debian/Ubuntu-based)
        - Linux (Autres)
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system version
      placeholder: “Example: Windows 11 Professional 21H2 Build 22000.739”
    validations:
        required: true
  - type: input
    attributes:
      label: Hash of the commit on which the bug is encountered
      placeholder: 961108713a19d26c3325d16bcfa7afdbbea6ec2c
  - type: textarea
    attributes:
      label: Expected behavior
      description: A description of what should happen
      placeholder: The launcher should...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: A description of what happens with the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Instructions for reproducing the goal
      placeholder: |
        1. Open launcher
        2. Go to xyz menu
        3. Click on abc
        4. Watch
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional notes
      placeholder: Additional details about the bug, anything that might be useful
    validations:
      required: false
