blank_issues_enabled: false
contact_links:
  - name: Here is my Twitter, for any questions, requests or memes
    url: https://twitter.com/ElBenjas333
    about: Please do not open issues other than to report bugs
